In [8]:
import numpy as np
import sympy as sm
import math as m
import scipy as sc

# Берестов Иван Михайлович
ЛР №1, Вариант 2.


# 1) Используя библиотеку NumPy, cоздать матрицу 5x5 случайных вещественных чисел, принадлежащих интервалу (0, 2).Транспонировать. Вычислить ее определитель.

In [9]:
matrix = np.random.randint(0,3,(5, 5))
matrix

array([[0, 2, 1, 1, 2],
       [1, 2, 2, 2, 2],
       [0, 1, 1, 2, 1],
       [0, 1, 2, 1, 2],
       [1, 2, 0, 2, 1]])

In [10]:
matrix = matrix.transpose()
matrix

array([[0, 1, 0, 0, 1],
       [2, 2, 1, 1, 2],
       [1, 2, 1, 2, 0],
       [1, 2, 2, 1, 2],
       [2, 2, 1, 2, 1]])

In [11]:
np.linalg.det(matrix)

np.float64(1.9999999999999991)

# 2) Используя библиотеку NumPy, cоздать вектор-столбец и матрицу подходящих размеров. Выполнить умножение матриц.

In [12]:
matrix = np.random.randint(0,10,(2, 10))
matrix

array([[6, 5, 4, 9, 3, 3, 3, 6, 9, 8],
       [2, 0, 3, 0, 8, 0, 1, 0, 6, 8]])

In [13]:
vector = np.random.randint(0,10,(10,1))
vector

array([[7],
       [5],
       [6],
       [8],
       [0],
       [6],
       [6],
       [8],
       [1],
       [4]])

In [14]:
np.dot(matrix, vector)

array([[288],
       [ 76]])

# 3) Используя библиотеку SymPy, упростите выражение $\frac{28a}{b}(a+b)+(2a-7b)^2$
$a=\sqrt {3}$, $b=-3.42$

In [15]:
a,b = sm.symbols('a, b')
exp = (28*a / b) * (a + b) + (2*a - 7*b)**2
exp = exp.expand()
exp

4*a**2 + 28*a**2/b - 28*a*b + 28*a + 49*b**2

In [16]:
round(exp.subs([(a, m.sqrt(3)), (b, -3.42)]), 2)

774.92

# 4) Используя библиотеку SymPy, найдите частные производные от выражения из задания выше.

In [17]:
exp.diff(a)

8*a + 56*a/b - 28*b + 28

In [18]:
exp.diff(b)

-28*a**2/b**2 - 28*a + 98*b

# 5)Используя библиотеку NumPy, найти собственные векторы и собственные значения матрицы 
$A=\begin{pmatrix}
0 & -3 & -1 \\
3 & 8 & 2 \\
-7 & -15 & -3 \\
\end{pmatrix}$

In [19]:
A = np.array([[0,-3,-1],[3,8,2],[-7,-15,-3]])
np.linalg.eig(A)

EigResult(eigenvalues=array([1.+0.00000000e+00j, 2.+9.11086655e-08j, 2.-9.11086655e-08j]), eigenvectors=array([[ 4.08248290e-01+0.00000000e+00j,  1.35951347e-15+2.88110898e-08j,
         1.35951347e-15-2.88110898e-08j],
       [-4.08248290e-01+0.00000000e+00j, -3.16227766e-01-1.92073932e-08j,
        -3.16227766e-01+1.92073932e-08j],
       [ 8.16496581e-01+0.00000000e+00j,  9.48683298e-01+0.00000000e+00j,
         9.48683298e-01-0.00000000e+00j]]))

# 6)Вычислить интеграл двумя способами: используя библиотеку SciPy и библиотеку SymPy $\int_0^4\frac{dx}{1+\sqrt{2x+1}}$

In [24]:
sc.integrate.quad(lambda x: pow(1+m.sqrt(2*x+1),-1), 0, 4)

(1.3068528194401, 1.8467446721096826e-08)

In [34]:

sm.Integral(pow(1+sm.sqrt(2*x+1),-1),(x,0,4)).doit()

-log(4) + log(2) + 2

# 7)Вычислить интеграл двумя способами: используя библиотеку SciPy и библиотеку SymPy $\int_0^{\pi}dx\int_0^x cos(x + y)dy$

In [ ]:
def f(x, y):
    return cos(x + y)
def h(x):
    return x
v, err = integrate.dblquad(f, 0, pi() )